### ISSUE TITLE
例如点击B以后的复用的cell，dissMiss页面很耗时，需要再点击一次才能dissMiss掉页面

### ISSUE THREAD

**Issue by oldTilme** [qxuewei/XWCountryCode#2]
应该是点击第一屏以后的cell，即复用的cell，会这样，什么问题呢？

**Comment by qxuewei** [comment]
我用 UISearchController 重写了下Demo, 你看还有木有你说的问题

**Comment by 17770030995** [comment]
你好，我这边的问题是，点击了搜索出来的列表cell，不返回到主列表之前界面，请问怎么解决

**Comment by qxuewei** [comment]
> 你好，我这边的问题是，点击了搜索出来的列表cell，不返回到主列表之前界面，请问怎么解决

建议修改源码自行控制视图的跳转
